"""Alembic migration environment.

The database URL is taken from DATABASE_URL (env), falling back to the same
default as app.config — one source of truth across dev / CI / cluster. A migration
may target a throwaway database by setting DATABASE_URL (the tests do exactly this).

Migrations depend ONLY on the DB URL — deliberately NOT on the full app Settings,
so a migration Job never needs unrelated app secrets (e.g. JWT_SECRET) just to run.

`target_metadata` is the ORM models' metadata (S3), so `alembic revision
--autogenerate` diffs the DB against the models. The S2 initial migration was
hand-written; subsequent migrations may be autogenerated.
"""

from logging.config import fileConfig

from alembic import context
from pydantic_settings import BaseSettings, SettingsConfigDict
from sqlalchemy import engine_from_config, pool

from app.models import Base


class MigrationSettings(BaseSettings):
    """Migration-only settings: just the DB URL.

    Reads .env like the app does (so local `alembic` honours a dev DATABASE_URL),
    and an explicit DATABASE_URL env var still wins (tests rely on this). It does
    NOT pull in app secrets like JWT_SECRET — a migration Job shouldn't need them.
    """

    model_config = SettingsConfigDict(env_file=".env", extra="ignore")
    database_url: str = "postgresql+psycopg://modelmatch:modelmatch@localhost:5432/modelmatch"


config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

config.set_main_option("sqlalchemy.url", MigrationSettings().database_url)

# ORM models (S3) are the autogenerate target. The S2 migration was hand-written;
# from here on, `alembic revision --autogenerate` diffs the DB against these models.
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Emit SQL to a script without a live DB connection (`alembic upgrade --sql`)."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live database connection."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
