"""initial schema

Creates every ModelMatch entity (architecture.md §5) plus the `llm_usage` tally
(the hard-hourly-cap counter — handoff §4). Hand-written, not autogenerated: the
SQLAlchemy ORM models land in S3, so S2 is pure, reviewable DDL.

Design notes:
- NO embedding/vector columns anywhere — the recommender is deterministic and
  pgvector is dropped from the design. The round-trip test enforces this.
- Native PostgreSQL ENUM types only for the small, CLOSED, code-driven sets the
  app switches on (verdict, category, role, purpose, ...). Open, data-driven
  fields the LLM ingestion (#3) grows — `task_type`, `metric`, source kind/status
  — stay VARCHAR so a new value never needs a migration.
- Secret-bearing columns are named `*_ref` and carry comments: they hold a
  reference into a secret store, NEVER plaintext (architecture §9).

Revision ID: 20cc67750db7
Revises:
Create Date: 2026-06-04 14:25:58.173275
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg


# revision identifiers, used by Alembic.
revision: str = "20cc67750db7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --- Native PG ENUM types (closed, code-driven sets) -----------------------
# create_type=False: we create/drop them explicitly so downgrade fully reverses
# (a table drop does NOT drop its enum types — that's the classic Alembic gotcha).
data_policy = pg.ENUM("trains_on_input", "private", name="data_policy", create_type=False)
budget_sensitivity = pg.ENUM("low", "medium", "high", name="budget_sensitivity", create_type=False)
finding_category = pg.ENUM("security", "style", name="finding_category", create_type=False)
feedback_verdict = pg.ENUM("accept", "reject", name="feedback_verdict", create_type=False)
chat_role = pg.ENUM("user", "assistant", name="chat_role", create_type=False)
trace_kind = pg.ENUM("savings", "benchmark_result", name="trace_kind", create_type=False)
llm_purpose = pg.ENUM("ingestion", "chat", "agent", name="llm_purpose", create_type=False)
alert_kind = pg.ENUM("upgrade", "downgrade", name="alert_kind", create_type=False)

ENUMS = (
    data_policy,
    budget_sensitivity,
    finding_category,
    feedback_verdict,
    chat_role,
    trace_kind,
    llm_purpose,
    alert_kind,
)

# Reusable column types
_money = sa.Numeric(14, 6)  # prices, costs, savings, rank_score
_score = sa.Numeric(8, 4)   # benchmark scores (e.g. 42.2)


def upgrade() -> None:
    bind = op.get_bind()
    for enum in ENUMS:
        enum.create(bind, checkfirst=True)

    op.create_table(
        "user",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("email", sa.String(320), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(255), nullable=False),
    )

    op.create_table(
        "model",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("vendor", sa.String(100), nullable=False),
        sa.Column("price_per_mtok", _money),
        sa.Column("data_policy", data_policy),
        sa.UniqueConstraint("name", "vendor", name="uq_model_name_vendor"),
    )

    op.create_table(
        "harness",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("vendor", sa.String(100)),
    )

    op.create_table(
        "benchmark",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("task_type", sa.String(64)),  # open set (grown by ingestion #3)
    )

    op.create_table(
        "source_document",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("kind", sa.String(64)),
        sa.Column("uri", sa.String(1024)),
        sa.Column("s3_key", sa.String(1024)),
        # content_hash = idempotency key: re-ingesting an unchanged source is a no-op.
        sa.Column("content_hash", sa.String(64), nullable=False, unique=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True)),
        sa.Column("status", sa.String(32)),
    )

    op.create_table(
        "benchmark_result",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("model_id", sa.Integer, sa.ForeignKey("model.id"), nullable=False),
        sa.Column("harness_id", sa.Integer, sa.ForeignKey("harness.id")),
        sa.Column("benchmark_id", sa.Integer, sa.ForeignKey("benchmark.id"), nullable=False),
        sa.Column("task_type", sa.String(64)),
        sa.Column("score", _score),
        sa.Column("metric", sa.String(64)),  # open set: pass@1_percent, accuracy_percent, ...
        sa.Column("cost_per_mtok", _money),
        sa.Column("context_window", sa.Integer),
        sa.Column("source", sa.String(1024)),
        sa.Column("source_document_id", sa.Integer, sa.ForeignKey("source_document.id")),
        sa.Column("measured_at", sa.Date),
    )

    op.create_table(
        "requirements_profile",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("user.id"), nullable=False),
        # form-collected facets (NOT LLM-extracted, NO embedding)
        sa.Column("task_types", pg.ARRAY(sa.String(64))),
        sa.Column("budget_sensitivity", budget_sensitivity),
        sa.Column("latency_need", sa.String(32)),
    )

    op.create_table(
        "recommendation_option",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("profile_id", sa.Integer, sa.ForeignKey("requirements_profile.id"), nullable=False),
        sa.Column("rank", sa.Integer),
        sa.Column("rank_score", _money),  # deterministic w_q·quality + w_c·(1−cost)
        sa.Column("model_id", sa.Integer, sa.ForeignKey("model.id"), nullable=False),
        sa.Column("harness_id", sa.Integer, sa.ForeignKey("harness.id")),
        # provenance is FK-enforced via the recommendation_evidence join table below.
    )

    op.create_table(
        # Deterministic provenance: which benchmark_result rows informed each
        # recommendation_option. A join table (not an array column) so both ends
        # are real FKs — the DB rejects dangling references.
        "recommendation_evidence",
        sa.Column(
            "recommendation_option_id",
            sa.Integer,
            sa.ForeignKey("recommendation_option.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "benchmark_result_id",
            sa.Integer,
            sa.ForeignKey("benchmark_result.id"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "recommendation_option_id",
            "benchmark_result_id",
            name="pk_recommendation_evidence",
        ),
    )

    op.create_table(
        "project",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("user.id"), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("selected_option_id", sa.Integer, sa.ForeignKey("recommendation_option.id")),
        sa.Column("baseline_model_id", sa.Integer, sa.ForeignKey("model.id")),
    )

    op.create_table(
        "jenkins_connection",
        sa.Column("id", sa.Integer, primary_key=True),
        # UNIQUE → 1:1 with project
        sa.Column("project_id", sa.Integer, sa.ForeignKey("project.id"), nullable=False, unique=True),
        sa.Column("base_url", sa.String(1024)),
        sa.Column("job_name", sa.String(255)),
        sa.Column(
            "jenkins_token_ref",
            sa.String(255),
            comment="secret-store reference to the Jenkins API token — NEVER plaintext",
        ),
        sa.Column(
            "model_api_key_ref",
            sa.String(255),
            comment="secret-store reference to the BYOK model key — NEVER plaintext",
        ),
        sa.Column("status", sa.String(32)),
    )

    op.create_table(
        "ci_run",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("project_id", sa.Integer, sa.ForeignKey("project.id"), nullable=False),
        sa.Column("jenkins_build_id", sa.String(255)),
        sa.Column("model_id", sa.Integer, sa.ForeignKey("model.id")),
        sa.Column("task", sa.String(32), nullable=False, server_default="code_review"),
        sa.Column("tokens_in", sa.Integer),
        sa.Column("tokens_out", sa.Integer),
        sa.Column("actual_cost", _money),
        sa.Column("baseline_cost", _money),
        sa.Column("savings", _money),
        sa.Column("quality_ok", sa.Boolean),
    )

    op.create_table(
        "ci_finding",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("ci_run_id", sa.Integer, sa.ForeignKey("ci_run.id"), nullable=False),
        sa.Column("severity", sa.String(32)),
        sa.Column("category", finding_category),
        sa.Column("file", sa.String(1024)),
        sa.Column("line", sa.Integer),
        sa.Column("message", sa.Text),
    )

    op.create_table(
        "finding_feedback",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("ci_finding_id", sa.Integer, sa.ForeignKey("ci_finding.id"), nullable=False),
        sa.Column("verdict", feedback_verdict, nullable=False),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("user.id")),
    )

    op.create_table(
        "chat_message",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("project_id", sa.Integer, sa.ForeignKey("project.id"), nullable=False),
        sa.Column("role", chat_role, nullable=False),
        sa.Column("text", sa.Text),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "retrieval_trace",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("chat_message_id", sa.Integer, sa.ForeignKey("chat_message.id"), nullable=False),
        sa.Column("kind", trace_kind, nullable=False),  # what grounded the answer
        sa.Column("ref", sa.String(255)),
        sa.Column("snippet", sa.Text),
    )

    op.create_table(
        "llm_call",
        sa.Column("id", sa.Integer, primary_key=True),
        # nullable: ingestion/chat have no ci_run; the agent's runs live in the user's CI.
        sa.Column("ci_run_id", sa.Integer, sa.ForeignKey("ci_run.id")),
        sa.Column("purpose", llm_purpose, nullable=False),
        sa.Column("model_id", sa.Integer, sa.ForeignKey("model.id")),
        sa.Column("tokens_in", sa.Integer),
        sa.Column("tokens_out", sa.Integer),
        sa.Column("latency_ms", sa.Integer),
        sa.Column("status", sa.String(32)),
    )

    op.create_table(
        "proactive_alert",  # SEPARABLE (feature-flagged advisor)
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("project_id", sa.Integer, sa.ForeignKey("project.id"), nullable=False),
        sa.Column("kind", alert_kind, nullable=False),
        sa.Column("reason", sa.Text),
        sa.Column("evidence", pg.JSONB),
        sa.Column("status", sa.String(32)),
    )

    op.create_table(
        "llm_usage",
        # Replica-shared tally for the hard hourly token cap (LLM_HOURLY_TOKEN_CAP).
        # hour_start is the PK → atomic upsert/increment via ON CONFLICT.
        sa.Column("hour_start", sa.DateTime(timezone=True), primary_key=True),
        sa.Column("tokens_used", sa.BigInteger, nullable=False, server_default="0"),
    )


def downgrade() -> None:
    bind = op.get_bind()
    # Drop children before parents (reverse of create order).
    for table in (
        "llm_usage",
        "proactive_alert",
        "llm_call",
        "retrieval_trace",
        "chat_message",
        "finding_feedback",
        "ci_finding",
        "ci_run",
        "jenkins_connection",
        "project",
        "recommendation_evidence",
        "recommendation_option",
        "requirements_profile",
        "benchmark_result",
        "source_document",
        "benchmark",
        "harness",
        "model",
        "user",
    ):
        op.drop_table(table)

    # Table drops don't drop enum types — remove them explicitly.
    #
    # This blanket "drop every enum type" is correct ONLY because this is the
    # INITIAL migration: downgrading it tears the whole schema down, so every
    # table that uses these types has already been dropped above and no usage
    # remains. Do NOT copy this pattern into a later partial migration. A future
    # migration must drop an enum type only when it removes that type's FINAL
    # usage (the last table/column referencing it) — dropping a still-referenced
    # type will fail, and dropping one whose usage another migration owns corrupts
    # history. checkfirst=True keeps the teardown idempotent.
    for enum in ENUMS:
        enum.drop(bind, checkfirst=True)
