"""catalog uniqueness constraints

Natural keys that make catalog ingestion / seed loading idempotent (S5):
- benchmark.name unique; harness (name, vendor) unique.
- benchmark_result unique on (model, benchmark, harness, metric) — the ON CONFLICT
  target for the upsert.
All multi-col keys with a nullable column use NULLS NOT DISTINCT (PG15+) so NULLs
(no harness, no harness vendor) still dedupe. Autogenerated from the ORM (S3 wiring).

Revision ID: ae527d20dc5a
Revises: 20cc67750db7
Create Date: 2026-06-05 15:49:32.609909
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae527d20dc5a'
down_revision: Union[str, None] = '20cc67750db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_unique_constraint("uq_benchmark_name", "benchmark", ["name"])
    op.create_unique_constraint(
        "uq_harness_name_vendor",
        "harness",
        ["name", "vendor"],
        postgresql_nulls_not_distinct=True,
    )
    op.create_unique_constraint(
        "uq_benchmark_result_identity",
        "benchmark_result",
        ["model_id", "benchmark_id", "harness_id", "metric"],
        postgresql_nulls_not_distinct=True,
    )


def downgrade() -> None:
    op.drop_constraint("uq_benchmark_result_identity", "benchmark_result", type_="unique")
    op.drop_constraint("uq_harness_name_vendor", "harness", type_="unique")
    op.drop_constraint("uq_benchmark_name", "benchmark", type_="unique")
